//global.im = ['immersiveengineering']

//    event.hide(Item.of(''))


// Manage JEI Item Subtypes
KubeJEIEvents.subtypes(event => {
    // Hide the item "minecraft:stone" from JEI
    event.hide(Item.of('immersiveengineering:mold_plate'))
    event.hide(Item.of('immersiveengineering:mold_gear'))
    event.hide(Item.of('immersiveengineering:mold_rod'))
    event.hide(Item.of('immersiveengineering:mold_bullet_casing'))
    event.hide(Item.of('immersiveengineering:mold_wire'))
    event.hide(Item.of('immersiveengineering:mold_packing_4'))
    event.hide(Item.of('immersiveengineering:mold_packing_9'))
    event.hide(Item.of('immersiveengineering:mold_unpacking'))
    event.hide(Item.of('immersiveengineering:coal_coke'))
    event.hide(Item.of('immersiveengineering:waterwheel_segment'))
    event.hide(Item.of('immersiveengineering:windmill_blade'))
    event.hide(Item.of('immersiveengineering:dust_coke'))
    event.hide(Item.of('immersiveengineering:wire_copper'))
    event.hide(Item.of('immersiveengineering:wire_electrum'))


// Belts
    event.hide(Item.of('immersiveengineering:conveyor_extract'))
    event.hide(Item.of('immersiveengineering:conveyor_basic'))
    event.hide(Item.of('immersiveengineering:conveyor_redstone'))
    event.hide(Item.of('immersiveengineering:conveyor_dropper'))
    event.hide(Item.of('immersiveengineering:conveyor_vertical'))
    event.hide(Item.of('immersiveengineering:conveyor_splitter'))
    event.hide(Item.of('immersiveengineering:conveyor_extract'))

//chute
    event.hide(Item.of('immersiveengineering:chute_iron'))
    event.hide(Item.of('immersiveengineering:chute_steel'))
    event.hide(Item.of('immersiveengineering:chute_aluminum'))
    event.hide(Item.of('immersiveengineering:chute_copper'))
    event.hide(Item.of('immersiveengineering:chute_colored_white'))
    event.hide(Item.of('immersiveengineering:chute_colored_orange'))
    event.hide(Item.of('immersiveengineering:chute_colored_magenta'))
    event.hide(Item.of('immersiveengineering:chute_colored_light_blue'))
    event.hide(Item.of('immersiveengineering:chute_colored_yellow'))
    event.hide(Item.of('immersiveengineering:chute_colored_lime'))
    event.hide(Item.of('immersiveengineering:chute_colored_pink'))
    event.hide(Item.of('immersiveengineering:chute_colored_gray'))
    event.hide(Item.of('immersiveengineering:chute_colored_light_gray'))
    event.hide(Item.of('immersiveengineering:chute_colored_cyan'))
    event.hide(Item.of('immersiveengineering:chute_colored_purple'))
    event.hide(Item.of('immersiveengineering:chute_colored_blue'))
    event.hide(Item.of('immersiveengineering:chute_colored_brown'))
    event.hide(Item.of('immersiveengineering:chute_colored_green'))
    event.hide(Item.of('immersiveengineering:chute_colored_red'))
    event.hide(Item.of('immersiveengineering:chute_colored_black'))

//  ext
    event.hide(Item.of('immersiveengineering:manual'))
    event.hide(Item.of('immersiveengineering:wirecutter'))
    event.hide(Item.of('immersiveengineering:hammer'))
    event.hide(Item.of('immersiveengineering:survey_tools'))
    event.hide(Item.of('immersiveengineering:glider'))
    event.hide(Item.of('immersiveengineering:logic_circuit'))
    event.hide(Item.of('immersiveengineering:balloon'))
    event.hide(Item.of('immersiveengineering:cokebrick'))
    event.hide(Item.of('immersiveengineering:blastbrick'))
    event.hide(Item.of('immersiveengineering:blastbrick_reinforced'))
    event.hide(Item.of('immersiveengineering:alloybrick'))
    event.hide(Item.of('immersiveengineering:basic_engineering'))
    event.hide(Item.of('immersiveengineering:rs_engineering'))
    event.hide(Item.of('immersiveengineering:heavy_engineering'))
    event.hide(Item.of('immersiveengineering:light_engineering'))
    event.hide(Item.of('immersiveengineering:resonanz_engineering'))
    event.hide(Item.of('immersiveengineering:generator'))
    event.hide(Item.of('immersiveengineering:radiator'))
    event.hide(Item.of('immersiveengineering:circuit_table'))
    event.hide(Item.of('immersiveengineering:gunpowder_barrel'))
    event.hide(Item.of('immersiveengineering:wooden_barrel'))
    event.hide(Item.of('immersiveengineering:turntable'))
    event.hide(Item.of('immersiveengineering:crate'))
    event.hide(Item.of('immersiveengineering:reinforced_crate'))
    event.hide(Item.of('immersiveengineering:sorter'))
    event.hide(Item.of('immersiveengineering:item_batcher'))
    event.hide(Item.of('immersiveengineering:windmill'))
    event.hide(Item.of('immersiveengineering:watermill'))
    event.hide(Item.of('immersiveengineering:logic_unit'))
    event.hide(Item.of('immersiveengineering:fluid_sorter'))
    event.hide(Item.of('immersiveengineering:machine_interface'))
    event.hide(Item.of('immersiveengineering:capacitor_lv'))
    event.hide(Item.of('immersiveengineering:capacitor_mv'))
    event.hide(Item.of('immersiveengineering:capacitor_hv'))
    event.hide(Item.of('immersiveengineering:metal_barrel'))
    event.hide(Item.of('immersiveengineering:fluid_pump'))
    event.hide(Item.of('immersiveengineering:fluid_placer'))
    event.hide(Item.of('immersiveengineering:blastfurnace_preheater'))
    event.hide(Item.of('immersiveengineering:furnace_heater'))
    event.hide(Item.of('immersiveengineering:dynamo'))
    event.hide(Item.of('immersiveengineering:electric_lantern'))
    event.hide(Item.of('immersiveengineering:thermoelectric_generator'))
    event.hide(Item.of('immersiveengineering:fluid_pipe'))
    event.hide(Item.of('immersiveengineering:sample_drill'))
    event.hide(Item.of('immersiveengineering:cloche'))
    event.hide(Item.of('immersiveengineering:electromagnet'))
    event.hide(Item.of('immersiveengineering:pipe_valve'))
    event.hide(Item.of('immersiveengineering:hatch'))
    event.hide(Item.of('immersiveengineering:transformer'))
    event.hide(Item.of('immersiveengineering:transformer_hv'))
    event.hide(Item.of('immersiveengineering:breaker_switch'))
    event.hide(Item.of('immersiveengineering:redstone_breaker'))
    event.hide(Item.of('immersiveengineering:current_transformer'))
    event.hide(Item.of('immersiveengineering:toolbox'))
    event.hide(Item.of('immersiveengineering:voltmeter'))

// ore
    event.hide(Item.of("immersiveengineering:circuit_board"))
    event.hide(Item.of("immersiveengineering:plate_duroplast"))
    event.hide(Item.of("immersiveengineering:nugget_copper"))
    event.hide(Item.of("immersiveengineering:plate_copper"))
    event.hide(Item.of("immersiveengineering:ingot_aluminum"))
    event.hide(Item.of("immersiveengineering:nugget_aluminum"))
    event.hide(Item.of("immersiveengineering:raw_aluminum"))
    event.hide(Item.of("immersiveengineering:plate_aluminum"))
    event.hide(Item.of("immersiveengineering:ingot_lead"))
    event.hide(Item.of("immersiveengineering:nugget_lead"))
    event.hide(Item.of("immersiveengineering:raw_lead"))
    event.hide(Item.of("immersiveengineering:plate_lead"))
    event.hide(Item.of("immersiveengineering:ingot_silver"))
    event.hide(Item.of("immersiveengineering:nugget_silver"))
    event.hide(Item.of("immersiveengineering:raw_silver"))
    event.hide(Item.of("immersiveengineering:plate_silver"))
    event.hide(Item.of("immersiveengineering:ingot_nickel"))
    event.hide(Item.of("immersiveengineering:nugget_nickel"))
    event.hide(Item.of("immersiveengineering:raw_nickel"))
    event.hide(Item.of("immersiveengineering:plate_nickel"))
    event.hide(Item.of("immersiveengineering:ingot_uranium"))
    event.hide(Item.of("immersiveengineering:nugget_uranium"))
    event.hide(Item.of("immersiveengineering:raw_uranium"))
    event.hide(Item.of("immersiveengineering:plate_uranium"))
    event.hide(Item.of("immersiveengineering:ingot_constantan"))
    event.hide(Item.of("immersiveengineering:nugget_constantan"))
    event.hide(Item.of("immersiveengineering:plate_constantan"))
    event.hide(Item.of("immersiveengineering:ingot_electrum"))
    event.hide(Item.of("immersiveengineering:plate_electrum"))
    event.hide(Item.of("immersiveengineering:nugget_electrum"))
    event.hide(Item.of("immersiveengineering:ingot_steel"))
    event.hide(Item.of("immersiveengineering:nugget_steel"))
    event.hide(Item.of("immersiveengineering:plate_steel"))
    event.hide(Item.of("immersiveengineering:plate_iron"))
    event.hide(Item.of("immersiveengineering:plate_gold"))
    event.hide(Item.of("createbigcannons:cast_iron_ingot"))
    event.hide(Item.of("createbigcannons:steel_ingot"))



})
