ClientEvents.lang("en_us", event => {
    event.renameBlock('createendergateway:abandoned_gateway', 'Gateway Core')
    //event.renameItem('minecraft:', '')
    event.renameItem('immersiveengineering:armor_steel_helmet', 'Heavy Steel Helmet')
    event.renameItem('immersiveengineering:armor_steel_chestplate', 'Heavy Steel Chestplate')
    event.renameItem('immersiveengineering:armor_steel_leggings', 'Heavy Steel Legging')
    event.renameItem('immersiveengineering:armor_steel_boots', 'Heavy Steel Boots')
    event.renameItem('tfmg:rubber_sheet', 'Petroleum Rubber Sheet')
    event.renameItem('tfmg:silicon_ingot', 'Pure Silicon Ingot')
})
